### ISSUE TITLE
Can't configure cometchat in nuxtjs.

### ISSUE THREAD

**Issue by cxmanas** [cometchat-pro-samples/javascript-vuejs-chat-app#39]
### Describe the problem
I have gone though the documentation and tried to implement in our nuxtjs project, but it gives `reference error` or `window not defined` or `Unexpected token export`
> Provide a clear and concise description of the issue

### What was the expected behavior?
This should works seamlessly as it is working on the demo

> Tell us about the behavior you expected to see
It should work as documented.

### Environment

"nuxt": "^2.13.0",
"@cometchat-pro/chat": "^3.0.2-beta1",
![pcPC1WucD21fTOtj](https://github.com/cometchat-pro/cometchat-chat-sample-app-vue/assets/136781025/1dcc1250-361f-41dc-a487-9b00267c9400)
![image](https://github.com/cometchat-pro/cometchat-chat-sample-app-vue/assets/136781025/9f24a348-f4d7-48b1-b20c-065a91636c91)

**Comment by cxmanas** [comment]
Hi, Keagan
We have a nuxtjs project, and we stumbled upon cometchat, and followed the instruction from documentation [doc](https://www.cometchat.com/docs/vue-chat-ui-kit/integration-with-nuxt-js)

and then tried to run the project and go those above errors in different sequence.
Like most of the time we are getting window not defined.
![image](https://github.com/cometchat-pro/cometchat-chat-sample-app-vue/assets/136781025/000cd9de-4b1e-4232-b75e-6b209754fcba)

**Comment by isramv** [comment]
I am having the same issue, Nuxt 3 uses SSR and your library is trying to use the `window` object which is not available on the Front-end of the app.

**Comment by proveshapyne** [comment]
Hey @isramv,

Thanks for sharing. 
Please [submit a ticket](https://help.cometchat.com/hc/en-us/requests/new) with your concern so we can assist you with resolving the issue.

Provesha Pyne
CometChat Support
