### ISSUE TITLE
Nuxt3 Integration

### ISSUE THREAD

**Issue by getshaun24** [cometchat-pro-samples/javascript-vuejs-chat-app#44]
Please can you provide a guide on how to set up this UIkit with Nuxt3.

It seems that the current documentation is only for Nuxt2.

Thank You

**Comment by proveshapyne** [comment]
Hi @getshaun24 ,

Our [v3](https://www.cometchat.com/docs/vue-chat-ui-kit/overview) and [v4](https://www.cometchat.com/docs/v4/vue-uikit/overview) UI kits are both compatible with Vue2 and Vue3 and therefore supported by Nuxt3.
We have a [guide](https://www.cometchat.com/docs/vue-chat-ui-kit/integration-with-nuxt-js) for how to use our v3 UI Kit with Nuxt which will work with the v4 UI Kit as well.

I hope this helps!

Provesha Pyne
CometChat
